
language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  include:
    - php: 5.3
      env: deps=low

env:
  global:
    - deps=no

before_install:
  - composer self-update
  - cp app/config/parameters.yml.dist app/config/parameters.yml

install:
  - if [ "$deps" = "no" ]; then composer install; fi;
  - if [ "$deps" = "low" ]; then composer --prefer-lowest --prefer-stable update; fi;


script:
  - mkdir -p build/logs
  - phpunit -c app/ --log-json build/logs/logfile.json

after_script:
  - php vendor/bin/coveralls -v